TYPO3:
  Flow:
    http:
      chain:
        'process':
          chain:
            'redirection':
              position: 'before routing'
              component: 'Neos\RedirectHandler\RedirectionComponent'
